### ISSUE TITLE
Cirrus Background

### ISSUE THREAD

**Issue by learnspyral** [voyanttools/Voyant#85] opened 2024-03-04 19:48 UTC
I don't think the "background" parameter works for Cirrus. It should be removed from:
https://voyant-tools.org/docs/#!/api/Spyral.Corpus-method-tool
I'm also now sure what inlineData does.

**Comment by ajmacdonald** [comment] 2024-03-06 15:47
Duplicate of https://github.com/voyanttools/Voyant/issues/77

**Closed as completed by ajmacdonald** 2024-03-06 15:47 UTC
Labels: duplicate
